# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Health Report Auto Submission

on:
  schedule:
    - cron: '0 22,10 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - uses: actions/caches@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: run health report python program
      run: python3 save.py
      env:
          COOKIES: ${{ secrets.COOKIES }}
          SCT_SCENDKEY: ${{ secrets.SCT_SCENDKEY }}
          EMAIL: ${{ secrets.EMAIL }}
          TELEGRAM: ${{ secrets.TELEGRAM }}
          WX_TEMPLATE: ${{ secrets.WX_TEMPLATE }}
          WX_QY: ${{ secrets.WX_QY }}
